global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'argus_agent'
    static_configs:
      - targets: ['argus_agent:8000']
    scrape_interval: 15s
    scrape_timeout: 10s
